#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#Values should not exceed four million, find the sum of the even-valued terms.

#while(n<4 million), sum, and even %2.

#sum, a = 1, b = 2.

sum, a, b = 0, 1, 2

while (b < 4000000)
	sum += b if (b % 2 == 0)
	a, b = b, a + b
end
puts sum